"""Generate thesis-ready figures for the first E1 label-only experiment.

The script reads only preserved CSV artefacts from the frozen-vision and
Vision-LoRA runs. It writes every figure as PNG and SVG together with the
source values used to construct it.
"""

from __future__ import annotations

import csv
import json
from dataclasses import dataclass
from pathlib import Path
from typing import cast

import matplotlib.pyplot as plt
from matplotlib.ticker import PercentFormatter

plt.switch_backend("Agg")


PROJECT_ROOT = Path(__file__).resolve().parents[1]
OUTPUT_DIRECTORY = (
    PROJECT_ROOT
    / "annotations"
    / "training_steps"
    / "figures"
    / "01_e1_label_only_vision_ablation"
)
FROZEN_RUN = (
    PROJECT_ROOT
    / "outputs"
    / "training"
    / "e1_label_frozen_vision"
    / "full-l40s-frozen-seed3407-20260812"
)
VISION_RUN = (
    PROJECT_ROOT
    / "outputs"
    / "training"
    / "e1_label_unsloth_all"
    / "full-l40s-vision-seed3407-20260813"
)


@dataclass(frozen=True, slots=True)
class CheckpointMetric:
    """Validation metrics for one saved checkpoint."""

    condition: str
    epoch: int
    top1: float
    macro_f1: float
    balanced_accuracy: float


@dataclass(frozen=True, slots=True)
class ClassMetric:
    """Per-class F1 result for one condition."""

    label: str
    support: int
    frozen_f1: float
    vision_f1: float

    @property
    def difference(self) -> float:
        """Return Vision-LoRA minus frozen-vision F1."""

        return self.vision_f1 - self.frozen_f1


def _required_float(payload: dict[str, object], key: str) -> float:
    """Return one required numeric JSON field as a float."""

    value = payload.get(key)
    if not isinstance(value, int | float):
        raise ValueError(f"Expected numeric field {key!r} in preserved metrics.")
    return float(value)


def _read_base_metrics(run_directory: Path) -> CheckpointMetric:
    """Read the deterministic pre-update evaluation of the base model."""

    path = run_directory / "metrics" / "sft_dev__base.json"
    payload = cast(dict[str, object], json.loads(path.read_text(encoding="utf-8")))
    return CheckpointMetric(
        condition="Base",
        epoch=0,
        top1=_required_float(payload, "top1_accuracy"),
        macro_f1=_required_float(payload, "macro_f1"),
        balanced_accuracy=_required_float(payload, "balanced_accuracy"),
    )


def _read_resource_metric(run_directory: Path, metric: str) -> float:
    """Read one scalar from a run's preserved resource summary."""

    path = run_directory / "tables" / "resource_summary.csv"
    with path.open(encoding="utf-8", newline="") as handle:
        values = {row["metric"]: float(row["value"]) for row in csv.DictReader(handle)}
    try:
        return values[metric]
    except KeyError as exc:
        raise ValueError(f"Missing resource metric {metric!r} in {path}.") from exc


def _read_checkpoint_metrics(
    run_directory: Path,
    condition: str,
) -> list[CheckpointMetric]:
    """Read checkpoint metrics generated by the training pipeline."""

    path = run_directory / "tables" / "checkpoint_metrics.csv"
    with path.open(encoding="utf-8", newline="") as handle:
        return [
            CheckpointMetric(
                condition=condition,
                epoch=int(float(row["epoch"])),
                top1=float(row["top1"]),
                macro_f1=float(row["macro_f1"]),
                balanced_accuracy=float(row["balanced"]),
            )
            for row in csv.DictReader(handle)
        ]


def _read_per_class(run_directory: Path) -> dict[str, tuple[int, float]]:
    """Read support and F1 for each diagnostic class."""

    path = run_directory / "tables" / "per_class_metrics.csv"
    with path.open(encoding="utf-8", newline="") as handle:
        return {
            row["label"]: (int(row["support"]), float(row["f1"]))
            for row in csv.DictReader(handle)
        }


def _write_csv(
    path: Path,
    header: tuple[str, ...],
    rows: list[tuple[object, ...]],
) -> None:
    """Write source values for a generated figure."""

    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.writer(handle)
        writer.writerow(header)
        writer.writerows(rows)


def _save_figure(figure: plt.Figure, stem: str) -> None:
    """Save one figure in raster and vector formats."""

    figure.savefig(OUTPUT_DIRECTORY / f"{stem}.png", dpi=300, bbox_inches="tight")
    figure.savefig(OUTPUT_DIRECTORY / f"{stem}.svg", bbox_inches="tight")
    plt.close(figure)


def _plot_checkpoint_trajectories(
    metrics: list[CheckpointMetric],
    base: CheckpointMetric,
) -> None:
    """Plot both training conditions across the three epochs."""

    panels = (
        ("top1", "Top-1 accuracy"),
        ("macro_f1", "Macro-F1"),
        ("balanced_accuracy", "Balanced accuracy"),
    )
    colors = {"Frozen vision": "#3366AA", "Vision LoRA": "#DD7733"}
    figure, axes = plt.subplots(1, 3, figsize=(12.6, 4.2), sharey=True)
    for axis, (attribute, title) in zip(axes, panels, strict=True):
        for condition in colors:
            condition_rows = [row for row in metrics if row.condition == condition]
            condition_rows.sort(key=lambda row: row.epoch)
            epochs = [0, *[row.epoch for row in condition_rows]]
            values = [
                getattr(base, attribute),
                *[getattr(row, attribute) for row in condition_rows],
            ]
            axis.plot(
                epochs,
                values,
                marker="o",
                linewidth=2.2,
                color=colors[condition],
                label=condition,
            )
        axis.set_title(title)
        axis.set_xlabel("Epoch")
        axis.set_xticks((0, 1, 2, 3))
        axis.grid(alpha=0.25)
        axis.yaxis.set_major_formatter(PercentFormatter(1.0))
    axes[0].set_ylabel("Score on sft_dev")
    axes[0].set_ylim(0.30, 0.67)
    handles, labels = axes[-1].get_legend_handles_labels()
    figure.legend(
        handles,
        labels,
        loc="lower center",
        bbox_to_anchor=(0.5, 0.055),
        ncol=2,
        frameon=False,
    )
    figure.suptitle(
        "E1 label-only: validation trajectory by visual adaptation condition"
    )
    figure.text(
        0.5,
        0.012,
        "sft_dev: 1,229 cases; training seed: 3407",
        ha="center",
        fontsize=9,
    )
    figure.tight_layout(rect=(0, 0.15, 1, 0.93))
    _save_figure(figure, "checkpoint_trajectories")

    rows: list[tuple[object, ...]] = [
        ("Base", 0, base.top1, base.macro_f1, base.balanced_accuracy)
    ]
    rows.extend(
        (row.condition, row.epoch, row.top1, row.macro_f1, row.balanced_accuracy)
        for row in metrics
    )
    _write_csv(
        OUTPUT_DIRECTORY / "checkpoint_trajectories_source.csv",
        ("condition", "epoch", "top1_accuracy", "macro_f1", "balanced_accuracy"),
        rows,
    )


def _plot_per_class_difference(class_metrics: list[ClassMetric]) -> None:
    """Plot the F1 effect of visual adaptation for every class."""

    ordered = sorted(class_metrics, key=lambda row: row.difference)
    labels = [row.label.replace("_", " ") for row in ordered]
    values = [100.0 * row.difference for row in ordered]
    colors = ["#2E8B57" if value >= 0 else "#B84A4A" for value in values]

    figure, axis = plt.subplots(figsize=(10.8, 8.2))
    bars = axis.barh(labels, values, color=colors)
    axis.axvline(0, color="black", linewidth=0.9)
    axis.set_xlabel("Difference in F1 (Vision LoRA - frozen vision), percentage points")
    axis.set_title("Per-class effect of adapting visual layers")
    axis.grid(axis="x", alpha=0.25)
    axis.bar_label(
        bars,
        labels=[
            f"{value:+.1f}  (n={row.support})"
            for value, row in zip(values, ordered, strict=True)
        ],
        padding=3,
        fontsize=8,
    )
    axis.set_xlim(min(values) - 4, max(values) + 8)
    figure.text(
        0.5,
        0.01,
        "Green indicates higher F1 with Vision LoRA; n is the sft_dev class support.",
        ha="center",
        fontsize=9,
    )
    figure.tight_layout(rect=(0, 0.035, 1, 1))
    _save_figure(figure, "per_class_f1_difference")
    _write_csv(
        OUTPUT_DIRECTORY / "per_class_f1_difference_source.csv",
        ("label", "support", "frozen_f1", "vision_f1", "difference_f1"),
        [
            (row.label, row.support, row.frozen_f1, row.vision_f1, row.difference)
            for row in ordered
        ],
    )


def _plot_quality_and_cost(metrics: list[CheckpointMetric]) -> None:
    """Show quality and compute cost without a truncated common axis."""

    conditions = ("Frozen vision", "Vision LoRA")
    macro_f1 = tuple(
        100.0 * max(row.macro_f1 for row in metrics if row.condition == condition)
        for condition in conditions
    )
    gpu_hours = (
        _read_resource_metric(FROZEN_RUN, "gpu_hours"),
        _read_resource_metric(VISION_RUN, "gpu_hours"),
    )
    colors = ("#3366AA", "#DD7733")
    figure, axes = plt.subplots(1, 2, figsize=(8.6, 4.5))
    quality_bars = axes[0].bar(conditions, macro_f1, color=colors)
    cost_bars = axes[1].bar(conditions, gpu_hours, color=colors)
    axes[0].set_title("Validation quality")
    axes[0].set_ylabel("Macro-F1 (%)")
    axes[0].set_ylim(0, 70)
    axes[0].bar_label(quality_bars, fmt="%.2f%%", padding=3)
    axes[1].set_title("Training cost")
    axes[1].set_ylabel("GPU-hours")
    axes[1].set_ylim(0, 2.5)
    axes[1].bar_label(cost_bars, fmt="%.3f", padding=3)
    for axis in axes:
        axis.grid(axis="y", alpha=0.25)
        axis.tick_params(axis="x", rotation=12)
    figure.suptitle("Quality-cost trade-off of visual-layer LoRA")
    figure.tight_layout(rect=(0, 0, 1, 0.93))
    _save_figure(figure, "quality_cost_tradeoff")
    _write_csv(
        OUTPUT_DIRECTORY / "quality_cost_tradeoff_source.csv",
        ("condition", "macro_f1", "gpu_hours"),
        [
            ("frozen_vision", macro_f1[0] / 100.0, gpu_hours[0]),
            ("vision_lora", macro_f1[1] / 100.0, gpu_hours[1]),
        ],
    )


def main() -> None:
    """Generate every curated figure and its source table."""

    OUTPUT_DIRECTORY.mkdir(parents=True, exist_ok=True)
    checkpoint_metrics = [
        *_read_checkpoint_metrics(FROZEN_RUN, "Frozen vision"),
        *_read_checkpoint_metrics(VISION_RUN, "Vision LoRA"),
    ]
    base_metrics = _read_base_metrics(FROZEN_RUN)
    frozen_classes = _read_per_class(FROZEN_RUN)
    vision_classes = _read_per_class(VISION_RUN)
    if frozen_classes.keys() != vision_classes.keys():
        raise ValueError(
            "The compared runs do not contain the same diagnostic classes."
        )
    class_metrics = [
        ClassMetric(
            label=label,
            support=frozen_classes[label][0],
            frozen_f1=frozen_classes[label][1],
            vision_f1=vision_classes[label][1],
        )
        for label in frozen_classes
    ]
    _plot_checkpoint_trajectories(checkpoint_metrics, base_metrics)
    _plot_per_class_difference(class_metrics)
    _plot_quality_and_cost(checkpoint_metrics)


if __name__ == "__main__":
    main()
