"""E3 hard-KD contracts and task-isolated teacher-target rendering."""

from src.train.e3.domain import (
    ConfidenceLevel,
    ContextDecision,
    ContextRequest,
    DiagnosticAssessment,
    DifferentialDiagnosis,
    ImageAssessment,
    InformationSufficiency,
    MissingDiscriminator,
    Observation,
    ObservationStatus,
    ProviderSafetyCategory,
    ResponsePolicy,
    RiskLevel,
    StageATarget,
    StageBCorrection,
    StageBTarget,
    StageReviewStatus,
    TeacherGenerationProvenance,
    TeacherGenerationStatus,
    TeacherTargetBundle,
)
from src.train.e3.generation import E3TeacherGenerationRunner
from src.train.e3.generation_config import (
    E3TeacherGenerationConfig,
    E3TerminologyConfig,
    load_e3_teacher_generation_config,
)
from src.train.e3.generation_data import (
    E3Candidate,
    E3Selection,
    E3TeacherSample,
    load_selected_images,
    select_e3_samples,
)
from src.train.e3.generation_records import (
    E3ArtifactStore,
    E3StageArtifact,
    E3TeacherBundleRecord,
)
from src.train.e3.phase import (
    E3FormattedExample,
    E3HardKDPhase,
    E3TrainingSample,
    E3TrainingVariant,
)
from src.train.e3.progress import (
    E3CampaignSpec,
    E3CampaignState,
    E3GenerationStage,
    E3ProgressEvent,
    E3ProgressPaths,
    E3ProgressStore,
    render_html,
    render_terminal,
)
from src.train.e3.prompts import (
    RenderedTeacherPrompt,
    StageAPromptResource,
    StageBPromptResource,
    render_stage_a_prompt,
    render_stage_b_prompt,
    stage_a_output_schema,
    stage_b_output_schema,
)
from src.train.e3.rendering import (
    DeterministicContextPolicyRenderer,
    DeterministicGroundedDifferentialRenderer,
    RenderedContextPolicy,
    RenderedGroundedDifferential,
    canonical_stage_a_json,
)
from src.train.e3.templates import (
    GROUNDED_DIFFERENTIAL_TEMPLATES,
    GroundedDifferentialTemplate,
)
from src.train.e3.terminology import (
    ConceptCategory,
    DermatologyTerminology,
    ImageModality,
    ImageObservability,
    TerminologyConcept,
    TerminologySource,
    load_dermatology_terminology,
    terminology_resource_sha256,
)

__all__ = [
    "GROUNDED_DIFFERENTIAL_TEMPLATES",
    "ConceptCategory",
    "ConfidenceLevel",
    "ContextDecision",
    "ContextRequest",
    "DermatologyTerminology",
    "DeterministicContextPolicyRenderer",
    "DeterministicGroundedDifferentialRenderer",
    "DiagnosticAssessment",
    "DifferentialDiagnosis",
    "E3ArtifactStore",
    "E3CampaignSpec",
    "E3CampaignState",
    "E3Candidate",
    "E3FormattedExample",
    "E3GenerationStage",
    "E3HardKDPhase",
    "E3ProgressEvent",
    "E3ProgressPaths",
    "E3ProgressStore",
    "E3Selection",
    "E3StageArtifact",
    "E3TeacherBundleRecord",
    "E3TeacherGenerationConfig",
    "E3TeacherGenerationRunner",
    "E3TeacherSample",
    "E3TerminologyConfig",
    "E3TrainingSample",
    "E3TrainingVariant",
    "GroundedDifferentialTemplate",
    "ImageAssessment",
    "ImageModality",
    "ImageObservability",
    "InformationSufficiency",
    "MissingDiscriminator",
    "Observation",
    "ObservationStatus",
    "ProviderSafetyCategory",
    "RenderedContextPolicy",
    "RenderedGroundedDifferential",
    "RenderedTeacherPrompt",
    "ResponsePolicy",
    "RiskLevel",
    "StageAPromptResource",
    "StageATarget",
    "StageBCorrection",
    "StageBPromptResource",
    "StageBTarget",
    "StageReviewStatus",
    "TeacherGenerationProvenance",
    "TeacherGenerationStatus",
    "TeacherTargetBundle",
    "TerminologyConcept",
    "TerminologySource",
    "canonical_stage_a_json",
    "load_dermatology_terminology",
    "load_e3_teacher_generation_config",
    "load_selected_images",
    "render_html",
    "render_stage_a_prompt",
    "render_stage_b_prompt",
    "render_terminal",
    "select_e3_samples",
    "stage_a_output_schema",
    "stage_b_output_schema",
    "terminology_resource_sha256",
]
